# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-12 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='cpu',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='time',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.TextField(default=b'toto'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='rating',
            field=models.IntegerField(default=10),
        ),
    ]
