# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-12 16:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20161012_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='process_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
