# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-12 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_algorithm_process_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='button',
            field=models.TextField(default=b' bootstrap_button \'\'  button_class="btn-primary"  button_type=\'link\' href=\'misc\'  size=\'sm\' icon=\'info-sign\' '),
        ),
    ]
