# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-13 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_algorithm_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='button',
            field=models.TextField(default=b'btn-primary'),
        ),
    ]
