# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-13 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20161013_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='time',
            field=models.FloatField(default=10),
        ),
    ]
