# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-13 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20161013_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='run_id',
            field=models.IntegerField(default=10),
        ),
    ]
