# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-26 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_algorithm_run_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='id',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='ranking',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='run_id',
            field=models.CharField(editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
