# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-26 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20161026_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='ranking',
            field=models.IntegerField(default=1),
        ),
    ]
